input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  if [service] == "backend" {
    mutate { add_field => { "[@metadata][index]" => "jelling-backend" } }
  } else if [service] == "sentiment" {
    mutate { add_field => { "[@metadata][index]" => "jelling-sentiment" } }
  } else {
    mutate { add_field => { "[@metadata][index]" => "jelling-general" } }
  }
  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
