apiVersion: v1
kind: Secret
metadata:
  name: jelling-secrets
  namespace: jelling
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vamVsbGluZzpqZWxsaW5nMTIzQHBvc3RncmVzOjU0MzIvamVsbGluZw==
  JWT_SECRET_KEY: cHJvZC1zZWNyZXQtY2hhbmdlLW1l
  POSTGRES_PASSWORD: amVsbGluZzEyMw==
